Repository DSCKGEC/NASA-Collision-Detection, pull requests merged in 2022-07, with the labels that each got.

#13 Added Logistic Regression analysis with accuracy
  Nasa_nearest_earth_object_classifier.ipynb
Labels: KSoC’22, medium

#17 uni_bi_variate_analysis
  .ipynb_checkpoints/Nasa_nearest_earth_object_classifier-checkpoint.ipynb
  Nasa_nearest_earth_object_classifier.ipynb
Labels: KSoC’22, medium

#18 Added Random Forest Classifier Model
  Nasa_nearest_earth_object_classifier.ipynb
Labels: KSoC’22, hard

#19 code documentation
  .ipynb_checkpoints/Nasa_nearest_earth_object_classifier-checkpoint.ipynb
  Nasa_nearest_earth_object_classifier.ipynb
Labels: KSoC’22, easy
